### ISSUE TITLE
 For Loan Amount, add in numeric max and min values for any range

### ISSUE THREAD

**Issue by kbmorales** [DataKind-DC/CARES#10]
posted by @JohnMcCambridge

- [x] create for each loan that has no specific LoanAmount a numeric max/min value, to allow for quick computation of max/min totals
- [x] for entries with specific LoanAmount values, use those as they are

**Comment by JohnMcCambridge** [comment]
I have committed a script with this to my repo: https://github.com/JohnMcCambridge/CARES/commit/def9780a419f9aa5807dd3968f07acba21af12c5

**Comment by JohnMcCambridge** [comment]
closing this as it appears this functionality is working well.
