### ISSUE TITLE
Improve NAICS matching

### ISSUE THREAD

**Issue by JohnMcCambridge** [DataKind-DC/CARES#42]
I am seeing evidence that some (all?) of the unmatched codes may be older, e.g., 722110: that's a valid 2007 NAICS code
it's possible different lenders use different code-years, or perhaps everyone is using old codes
It might be best to iterate through and if a match fails, go to the next newest code year list?

**Comment by kbmorales** [comment]
Incorporated NAICS hierarchical joins (i.e., if joining on the 2017 NAICS codes, try 2012, etc.) has dropped the failed matches from 228,384 to 219645.

Failed NAICS codes after this are:

```
111115 233110 233210 233220 233310 233320 235110 235210 235310 235510 235610 235710 235810 235930 235990 421110 421120 421320 421420 421450 421490 421510 421830 421850 421910 421920 421930 421940 421990 422110 422210 422310 422410 422710 422930 422990 452110 513111 513210 513310 513321 514110 514120 514199 514210 999990
```

Vast majority of NAICS join fails are `NA`s (60.6%) and `999990` (unknown; 39.3%). The remaining 0.1% are likely typos. Currently I'm not attempting at correcting them in any way systematically.

**Comment by JohnMcCambridge** [comment]
A google of some of those suggests they are from 1997 NAICS, I think. See e.g. "513310 Wired Telecommunications Carriers
This industry comprises establishments engaged in (1) operating and maintaining switching and transmission facilities to provide direct communications via landlines, microwave, or a combination of landlines and satellite linkups or (2) furnishing telegraph and other nonvocal communications using their own facilities." from https://www.census.gov/eos/www/naics/reference_files_tools/1997/sec51.htm

**Comment by kbmorales** [comment]
Ah naturally the one version of the NAICS codes they don't have a downloadable file for. >.<

**Comment by kbmorales** [comment]
Ah naturally the one version they don't have a downloadable index file for >.<

-------- Original Message --------

**Comment by JohnMcCambridge** [comment]
What about using the concordance table here: https://www.census.gov/eos/www/naics/concordances/concordances.html

(specifically: https://www.census.gov/eos/www/naics/concordances/1997_NAICS_to_2002_NAICS.xls)

Though if I understand your evaluation, even with the 1997 map perfect we would still only improve match rate by max 0.1%?

**Comment by kbmorales** [comment]
Oh good catch--I can trim that do basically be a 1997 code list.

but yes, correct, < 0.1% of the NAICS codes listed are unaccounted for in the other 4 NAICS dictionaries (2002-2017)
