### ISSUE TITLE
R package?

### ISSUE THREAD

**Issue by jimrothstein** [DataKind-DC/CARES#43]
Any thought to put code into [R package structure](https://r-pkgs.org/), even if goal is not to create a package?

**Comment by kbmorales** [comment]
Hey Jim. For now, basically treat the `code/` folder as if it's the `R/` folder in the usual package structure. Long story, but it's the directory structure we landed on.

If people are interested in creating a package for the project I'm all for it, though.

**Comment by kbmorales** [comment]
Hey @jimrothstein I've created a separate repo for an R package to ingest the data--feel free to try it out or if you'd like to work on it let me know.
[https://github.com/kbmorales/PPP](https://github.com/kbmorales/PPP)
