### ISSUE TITLE
Identify and attempt to correct data transposition/truncation issues

### ISSUE THREAD

**Issue by kbmorales** [DataKind-DC/CARES#9]
posted by @JohnMcCambridge

- [ ] flag impacted fields
- [ ] if possible, try and see if any of these issues spilled across rows: that would be Very Bad.

"There are 1,182 loans where numeric digits appear in the city field. Some of those are clearly spill overs or duplication from the address field. On 198 loan listings the city field contains an office suite number.

Quartz was able to identify 842 loans where what appears to be a name associated with the loan is listed in the city field. For 781 of those, the loaned amount was less than $150,000 which meant the recipients identity was intended to be withheld by the SBA. This error appears 824 times on loans processed by Bank of America.

A loan listed under Morgan-Keller Inc. says the company is at 70 THOMAS JOHNSON DRIVE in the city of SUITE 200 FREDERICK, MD rather than 70 Thomas Johnson Drive, Suite 200 in the city of Frederick, MD, as their website indicates.

A loan listed under Volta Power Systems LLC has its location listed as SUPERIOR CT in the city of 12550 HOLLAND, MI. On what appears to be the company’s website, a contact address of 12550 Superior Ct. Holland, MI is listed.

For 600 loans the city field contains a five-digit number. For 519 loans, that number matches the listed Zip code. In the loans where those fields don’t match, there are clearly data errors. A loan given to an unnamed business with an address at JFK Airport in New York is listed as being in Michigan. Its zip code is listed as 48851. It’s certainly not a coincidence that the industry code for “Freight Transportation Arrangement” is 488510." via https://qz.com/1878225/heres-what-we-know-is-wrong-with-the-ppp-data/

**Comment by emigre459** [comment]
I have a suspicion that solving this will solve a whole lot of our data problems. We shall see...

**Comment by emigre459** [comment]
Exploring these one "odd column" at a time, starting with `State`. Found a pattern in which all State values that are numeric are actually NAICS codes, and all data (except `LoanRange`) are shifted left by 2 columns. Wrote up code to push them back to where they should be, leaving NULLs in their wake. Fixing this seems to have fixed about 86% of all loan records in the full (state + 150K) dataset, albeit this is verified largely via spot checking and summary stats on a few well-defined fields (e.g. `Gender`).

**Comment by JohnMcCambridge** [comment]
Nicely done @emigre459. I think @zeinab is also working on this. Could I ask that as part of your process, you flag these rows in some way? What we're thinking is that a user should be able to filter easily any rows that have been flagged as having likely improper data / any rows which have been 'fixed'. That way we can 1) allow analysts to include or exclude 'fixed' data depending on their confidence in the fixes, 2) analyze 'fixed' rows to see if they show divergence from normal rows, perhaps revealing one particular bank, or state, or loan type was especially prone to errors.

**Comment by emigre459** [comment]
@JohnMcCambridge Sure, no problem, I'll flag problems and fixes rows via new columns. Is there a standard naming convention for those that I should follow? Perhaps something implemented in the R code already?

**Comment by emigre459** [comment]
~~To do: need to investigate the two columns I essentially destroy as part of the fix. Make sure they don't hold useful data.~~

All affected rows have nulls for the totality of these columns, so no issue there.

**Comment by JohnMcCambridge** [comment]
> @JohnMcCambridge Sure, no problem, I'll flag problems and fixes rows via new columns. Is there a standard naming convention for those that I should follow? Perhaps something implemented in the R code already?

I think look at some of the existing code, from myself and @zmousavi, a possible convention is '`ValidXXX`' where XXX is the original variable. But perhaps you plan to also record the manner of defect, in which case DefectXXX might also be useful? I'm fine with anything, and it's early enough for a new convention to emerge if there's some 'best practice' we can lean on.

**Comment by kbmorales** [comment]
Awesome work, y'all. I'm down with sticking to the `Valid`, but I'd love to rerun some stuff with the fix you propose. Is it ready for production?

**Comment by emigre459** [comment]
@kbmorales I still need to spend a little more time on it, maybe today. I need to check that I'm not dropping data from the two end columns that the transposition overwrites (probably not, but good to be thorough) and add the flag columns John mentioned (haven't had time to do that since his last message). I'll make a PR when it's ready.

**Comment by kbmorales** [comment]
No worries, this just looks like an awesome addition that should be added to the main data ingest pipe when ready. No rush!

**Comment by kbmorales** [comment]
After discussing with @emigre459 we found that this translocation is less of a standard data ingest task in the R pipeline, but should still be investigated. Unclear how the Quartz article compiled their data
